//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusRoute
    {
        public int BusRouteID { get; set; }
        public string RouteNumber { get; set; }
        public string RouteName { get; set; }
        public int ResponsibleUnitID { get; set; }
        public string OperationType { get; set; }
        public System.DateTime OperationTime { get; set; }
        public int Fare { get; set; }
        public int BusesAmount { get; set; }
        public System.DateTime BusesTime { get; set; }
        public System.DateTime BusesSpace { get; set; }
    }
}
